# ~/.config/starship.toml

format = '''
[â•­â•´](238)$os$username$hostname$directory$git_branch$git_status$git_commit$rust$python$dotnet $battery
[â•°â”€](238)$character '''

right_format = '''$memory_usage'''

[character]
error_symbol = "[â”€](bold #B4261A)"
success_symbol = "[â”€](238)"

[os]
format = "[$symbol]($style) "
style = "bold white"
disabled = false

[os.symbols]
Arch = "ğŸ—ï¸"
EndeavourOS = "ğŸš€"
Linux = "ğŸ§"
Macos = "ğŸ"
NixOS = "â„ï¸"
Ubuntu = "ğŸ¯"
Unknown = "â“"
Windows = "ğŸªŸ"

[battery]
format = '\[[$symbol$percentage]($style)\]'
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ '
discharging_symbol = 'ğŸ’€ '

[[battery.display]]
threshold = 100
style = "bold red"

[cmd_duration]
format = " took [$duration]($style)"
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)

[directory]
format = "[$path]($style)[$lock_symbol]($lock_style) "
style = "#ffbf67"
repo_root_style = "#ff7bb4"
truncation_length = 3
truncation_symbol = "â€¦/"
home_symbol = "ğŸ  ~"
read_only = ' ğŸ”’ '

[git_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = 'ğŸŒ± '
truncation_length = 4
truncation_symbol = 'â€¦/'
style = 'bold #f14e32'

[git_status]
conflicted = 'ğŸš©'
ahead = 'ğŸğŸ’¨ ${count}'
behind = 'ğŸ˜° ${count}'
diverged = 'ğŸ˜µâ‡¡${ahead_count}â‡£${behind_count}'
up_to_date = 'âœ…'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'

[git_commit]
commit_hash_length = 8
tag_symbol = "ğŸ”– "
style = "bold white"

[hostname]
ssh_only = true
format = " [$ssh_sybol$hostname]($style) at "
style = "bold #bb7dfb"
disabled = false

[username]
style_user = "bold #bb7dfb"
style_root = "bold black"
format = "[$user]($style) on"
show_always = false

[memory_usage]
format = '[$symbol \[$ram ~ $ram_pct\]]($style) '
threshold = 0
symbol = "ğŸ"
style = 'bold #459c50'
disabled = false

[python]
format = '\[[$symbol](bold #f7cb3f)[$version](bold #366c9c)\]'

[rust]
format = '\[[$symbol$version]($style)\]'
style = "bold #ac340f"

[dotnet]
format = '\[[$symbol$version]($style)\]'
style = "bold #5027d5"
version_format = '${raw}'
symbol = "ğŸ¥… "
heuristic = false

